### ISSUE TITLE
%game% template tag in Steam alert

### ISSUE THREAD

**Issue by njwest** [miskatonicstudio/intrepid#6] opened 2019-10-14 11:25 UTC
A Steam alert, I believe it is "Preparing to download ____..." shows up as "Preparing to download %game%..." after I do the following steps on macOS(not Catalina)

Couldn't screenshot it as the Steam alert disappeared before I had a chance to, also this could be an issue with the macOS Steam app rather than the game

**Steps to reproduce:**

1. Visit `Intrepid` Steam store page
2. Hit green "Play Game" button for the first time
3. Alert that pops up (and disappears quickly) says `Preparing to download %game%...` or something like that. I don't remember the alert, as it disappeared very quickly and the game started to download.

Thanks for the awesome open-source project :]

**Comment by miskatonicstudio** [comment] 2019-10-14 20:24
Thanks for reporting this :+1: I don't have any MacOS testers right now, so it will be difficult to confirm if this bug affects other versions of Apple products too. I just tested it on Linux and there was no alert pop-up (at least none that I would able to notice).

Nevertheless, I'll try to find an opportunity to confirm and fix this problem.

**Comment by miskatonicstudio** [comment] 2023-04-10 12:56
Closing as I'm unable to reproduce it. If it happens again, please reopen this ticket.

**Closed as completed by miskatonicstudio** 2023-04-10 12:56 UTC
